export const data = {
  users: [
    {
      name: "sifat100",
      email: "sifat100@gmail.com",
      password: "sifat100",
      phone: "0126547411",
      image: "https://i.ibb.co/K7GYBzw/Java-Script-logo.png",
      address: "Gognagar, Narayangonj",
    },
    {
      name: "sifat200",
      email: "sifat200@gmail.com",
      password: "sifat200",
      phone: "0126547411",
      image: "https://i.ibb.co/K7GYBzw/Java-Script-logo.png",
      address: "Gognagar, Narayangonj",
    },
    {
      name: "sifat300",
      email: "sifat300@gmail.com",
      password: "sifat300",
      phone: "0126547411",
      image: "https://i.ibb.co/K7GYBzw/Java-Script-logo.png",
      address: "Gognagar, Narayangonj",
    },
    {
      name: "sifat400",
      email: "sifat400@gmail.com",
      password: "sifat400",
      phone: "0126547411",
      image: "https://i.ibb.co/K7GYBzw/Java-Script-logo.png",
      address: "Gognagar, Narayangonj",
    },
    {
      name: "sifat500",
      email: "sifat500@gmail.com",
      password: "sifat100",
      phone: "0126547411",
      image: "https://i.ibb.co/K7GYBzw/Java-Script-logo.png",
      address: "Gognagar, Narayangonj",
    },
    {
      name: "sifat600",
      email: "sifat600@gmail.com",
      password: "sifat600",
      phone: "0126547411",
      image: "https://i.ibb.co/K7GYBzw/Java-Script-logo.png",
      address: "Gognagar, Narayangonj",
    },
    {
      name: "sifat700",
      email: "sifat700@gmail.com",
      password: "sifat700",
      phone: "0126547411",
      image: "https://i.ibb.co/K7GYBzw/Java-Script-logo.png",
      address: "Gognagar, Narayangonj",
    },
    {
      name: "sifat800",
      email: "sifat800@gmail.com",
      password: "sifat800",
      phone: "0126547411",
      image: "https://i.ibb.co/K7GYBzw/Java-Script-logo.png",
      address: "Gognagar, Narayangonj",
    },
    {
      name: "sifat900",
      email: "sifat900@gmail.com",
      password: "sifat900",
      phone: "0126547411",
      image: "https://i.ibb.co/K7GYBzw/Java-Script-logo.png",
      address: "Gognagar, Narayangonj",
    },
  ],
};
